hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
dataset:
  path: input/predict-meals

optimization:
  trials: 100
  params: best_lgbm.yaml
  

model:
  fold: 15
  params:
    n_estimators: 10000
    n_jobs: -1
    objective: mae
  early_stopping_rounds: 100
  verbose: False
search:
  study_name: TPE Search
  mode: tpe
  direction: minimize
  seed: 42
  min_resource: 1
  max_resource: auto
  reduction_factor: 3
  n_trials: 100
  verbose: False
  path_name: config/modeling/xgb.yaml
  params_name: config/tuning/xgb.yaml
  colsample_bytree:
  - 0.4
  - 1.0
  gamma:
  - 0.01
  - 0.1
  learning_rate:
  - 0.001
  - 0.01
  max_depth:
  - 2
  - 10
  min_child_weight:
  - 3
  - 10
  reg_alpha:
  - 0.001
  - 0.01
  reg_lambda:
  - 0.001
  - 0.01
  subsample:
  - 0.3
  - 1.0